### ISSUE TITLE
add workdir option

### ISSUE THREAD

**Issue by Nightreaver** [bossm8/dockerfile-templater#8]
Hello, 

we have several folders which contain image-specific files that will be added to the image.

The current way is to add the full path to dockerfile ie   
`COPY variants/{{ .image.name }}/{{ .image.tag }}/nginx.conf /etc/nginx/nginx.conf`  
This feels a bit bloated compare to the old way.  

I would suggest to add a "workdir" cmd option similar to "out.fmt" so I can use it like:
`COPY nginx-start.sh /nginx-start.sh`  in the dockerfile
and  
`--workdir.fmt variants/{{ .image.name }}/{{ .image.tag }}` or similar to switch the folder per commandline

**Comment by bossm8** [comment]
Isn't this more an issue with how the image is built rather than with the templater?

I.e. by setting the build context to `variants/<image.name>/<image.tag>` you can copy the files without needing the prefix in the Dockerfile:

```bash
for DF in $(find dockerfiles -type f); do
    NAME=$(echo ${DF} | awk -F '.' '{print $2}')
    TAG=$(echo ${DF} | awk -F '.' '{print $3}')
    docker build variants/${NAME}/${TAG} -f ${DF} -t ${NAME}:${TAG}
    # docker build . -f ${DF} -t ${NAME}:${TAG}
done
```

Otherwise you might also set the variable workdir in your template with `{{ $workdir := printf "variants/%s/%s" .image.name .image.tag }}` or in one of the yml input files.

Let me know if this solves your problem.
